# Generated by Django 5.2.4 on 2025-07-06 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cliente_dono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dono',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='codigo_tag',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='MembroProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('ADMIN', 'Administrador'), ('EDITOR', 'Editor'), ('VIEWER', 'Visualizador')], default='EDITOR', max_length=10)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to='api.projeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('projeto', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(related_name='projetos_participados', through='api.MembroProjeto', to=settings.AUTH_USER_MODEL),
        ),
    ]
